### ISSUE TITLE
Helm deployment integration is not available 

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#10]
Hello team, though its not focus on workload, but still its better to show helm deployment integration in combination with Flux.
We are new to AKS, Please give one sample here.

**Comment by ferantivero** [comment]
thanks for sharing your feedback @nitinkhandelwal26, please let us share with you [the official Flux docs](https://docs.fluxcd.io/en/1.20.0/tutorials/get-started-helm/) for getting it deployed using Helm. 

We're planning for more Reference Implementations in the future, and we're sure we will explore other more convenient ways to land Flux in the AKS clusters 😸 

Please stay tuned.

cc/ @doodlemania2

**Comment by ckittel** [comment]
Also @nitinkhandelwal26 we have some [AKS + Helm documentation that you can follow](https://docs.microsoft.com/azure/aks/kubernetes-helm).  You correctly identified that this implementation does not venture into Helm, let alone Helm + Flux.  Looking forward to telling that story soon!
