### ISSUE TITLE
Warning in CSI logs

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#100]
Hello Team,

I just encountered one warning in CSI logs
kubectl logs csi-secrets-store-9wr95 -n cluster-baseline-settings -c secrets-store
![CSI warning](https://user-images.githubusercontent.com/10863548/97537020-1e81e800-19e4-11eb-8b49-87df5272c6cb.PNG)

Though it's not an issue and doesn't know how it will impact the CSI store. just to bring into your notice..

**Comment by ckittel** [comment]
Good to know.  Do you know what pod that is?  It's in namespace `dafdev01`  Is it the ingress controller?

**Comment by ckittel** [comment]
Also, I'd ask upstream on the secret-store-csi-provider what that means and how one should respond if you're curious.

**Comment by nitinkhandelwal26** [comment]
namespace: dafdev01 is the same as a0008.

**Comment by ckittel** [comment]
Thanks.  I'm going to roll this information into #95 and address it when I pick up that task.

**Comment by ckittel** [comment]
Thanks.  Closing this one!
