### ISSUE TITLE
Service Mesh

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#108]
Hello Team,

Looking for Guidance on implementing Service Mesh from Infrastructure point.
Do you have any references or roadmap of this implementation?

Regards,

**Comment by ckittel** [comment]
Hey there. Only guidance that we have, that I'm aware of, is found @ <https://docs.microsoft.com/azure/aks/servicemesh-about>.  On the AKS Roadmap, we do have [Open Service Mesh](https://openservicemesh.io/) being developed as an out-of-the-box AddOn.  So if you want to go with an eventually-supported implementation, you might want to consider taking a dependency on OSM.

The work for that is currently ongoing.  No previews of it yet.

**Comment by nitinkhandelwal26** [comment]
Thanks, @ckittel, I just want to evaluate this, our production will be in August 2021. and during that time it might be used to solve the purpose of Canary and Phased Rollouts. This is the only use-case I have considered right now in which this can be helpful after production.
Any thoughts on this consideration?

**Comment by ckittel** [comment]
Understood. Well, feel free to evaluate the above items to see what works best for your specific needs. Alternatively, ingress controllers often can serve similar needs without adding/managing another in-cluster component. Really, your individual requirements, management/operations expectations, support expectations (OSS vs paid), and similar will hopefully land you in a good spot.

If we do publish any deep dives in this topic, I'll try to remember to make you aware. Likewise, if you have any learnings from your own exploration, you're welcome to share as well :)
