### ISSUE TITLE
cluster-stamp.json throw error if previous script were being run with different location

### ISSUE THREAD

**Issue by spotakash** [mspnp/aks-secure-baseline#115]
cluster-baseline-settings/user-facing-cluster-role-aad-group.yaml does not allow to operate location parameter. In all previous script, i used --location southeastasia. When i ran this script it threw error, after digging inside script i noticed that location is being mapped with georedundant location, thus it become difficult. In order to over this, i had to change default location for main location and georedundant location.

**Comment by ckittel** [comment]
Hey tehre @spotakash  -- can you help me understand your issue a little more?

In `cluster-stamp.json` the `geoRedundancyLocation` is used exclusively for Azure Container Registry's geo-replication location.  Furthermore, `cluster-baseline-settings/user-facing-cluster-role-aad-group.yaml` is location agnostic.  The only values in there are your Azure AD security group mapping.  That configuration isn't region dependant.  I also don't know what `--location souteastasia` would mean wrt this kubernetes manifest file.

Can you explain more about your situation, and maybe address the obversations I made above?  You might also consider including, what you tried to do and what you expected the outcome to be, but instead what was the outcome your received.

Thanks and have a great day.

**Comment by spotakash** [comment]
Hey @ckittel I shall try to provide what I did. 

I have been location as "southeastasia" as it is near to me in all the steps like vnet/resource group/aks cluster/...etc. 

During one of steps, my deployment keeps on failing (sorry I can't recall, I can run this lab again over weekend and give exact step). After looking into issue, i found that cluster-stamp.json default location (line 43/67) keeps on dragging value to default location while i have been using different location (southeastasia). Thus, I have to modify this cluster-stamp.json according to region i have been playing with i.e. Southeastasia (with redundant site to eastasia).

**Comment by ckittel** [comment]
Yes, please let us know what resource is being deployed to an unexpected location. I reviewed the template today and didn't see any reference to location outside of the two parameters, but it's possible something was missed. Thanks!

**Comment by ckittel** [comment]
Going to close this issue at this point. If there is more conversation you'd like to have around this, please let us know. Cheers.
