### ISSUE TITLE
Ingress controller[Question]

### ISSUE THREAD

**Issue by r1sharma** [mspnp/aks-secure-baseline#116]
Hi Team,

I am new to AKS and currently exploring to pick the right ingress controller for my cluster. I am curious why Traefik is picked in this reference implementation compare to other open source ingress controller(nginx/ambassador/kong etc)? 
Also how about AGIC? Given AGIC is a solution more closely aligned with Azure Gateway which can be the choice for standard load balancer, shouldn't that be seen as a good fit for AKS?
Please provide any reference/ experience in production with different ingress controller use.

**Comment by ckittel** [comment]
Hey there @r1sharma -- you are correct in identifying that you have many choices when it comes to ingress controllers.  The workload wasn't the focus of this reference implementation, so our requirements were pretty wide open in selection choices. As a reminder, this reference implementation is focused on the infrastructure side of AKS, not workload (which ingress is a significant factor in).  As for the reasons we chose Traefik here.
* We wanted to show OOS being part of the overall solution (as many customers like to Bring Their Own Solution to this area).
* We wanted to show how Key Vault can be used securely for certificates in an ingress controller, and Traefik works well enough to tell that story.  Traefik (or any third party OSS solution) allowed us to show off some of the features of the cluster a bit more directly.
* At the time of creating this reference implementation, AGIC was in preview and support was not a strong as support available for Traefik (which has both a community option and a paid option).
* Many advanced deployment techniques are well documented for Traefik (and other OOS) ingress controller, such as blue/green. AGIC doesn't have as many rich examples in that space, so to allow folks to have more self-help solutions for interesting deployment situations, we wanted to pick something that had a wider reach.

Ultimately, the ingress controller you use for your workloads should align with the support expectations, ability to manage to an SLO you need to achieve, and of course match up against all functional and other non-functional requirements for your workload.  AGIC can be a great fit if your use cases align, as can any of the other ingress controllers mentioned.  Ultimately the answer is "we had to pick one, and we picked one that would be interesting/relevant to show and start conversations :)"

**Comment by ckittel** [comment]
Going to close the question at this point.  If you have any more questions, don't hesitate to reach out.  Thanks!
