### ISSUE TITLE
VMSS does not support 1.18.2 and 1.18.4 

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/aks-secure-baseline#12]
Hi Team,

I am trying to create a cluster with AAD V2 Enable feature but facing below issue.

 ****""The AvailabilityProfile type of agentpool 'npsystem' is set to VirtualMachineScaleSets, but the Kubernetes version is 1.18.4(preview) which doesn't support VMSS."****

I have also faced issue while creating cluster with version 1.17 , AKS cluster node pool status was failed.

I am referring link: https://github.com/mspnp/aks-secure-baseline/blob/main/05-aks-cluster.md

Regards,
Rambabu

**Comment by ferantivero** [comment]
thanks for reporting this @rambabu0063, could you please share the outcome of deploying the AKS cluster using version `1.17.7`?

**Comment by ckittel** [comment]
Thank you for your interest in using this reference implementation with AKS 1.18 (preview) version, @rambabu0063.  We have not yet validated this reference implementation with the AKS 1.18 preview version.

You indicated an issue when you tried `1.17.7` -- was it related to the reference implementation or a configuration issue?  Can you share more information about that and any solution you had to resolve it or steps you took to troubleshoot.  Thanks.

**Comment by ckittel** [comment]
The tracking issue for AKS 1.18 can be found at #17.

We'll keep this issue open a little bit longer if you want help with the 1.17 issue you were facing but haven't detailed yet.  Otherwise, we'll close in a day or two and you can reopen as needed.  Thanks.
