### ISSUE TITLE
Update HTML version of readme

### ISSUE THREAD

**Issue by ckittel** [mspnp/aks-secure-baseline#120]
Diego, if you get some time, could you do a quick "sync" with the HTML content you added and the changes that have come about since that's landed.  It hasn't been maintained as the various files have changed.  If you think having it as an HTML file here is too much to maintain, your PR could be to remove it as well.  Really your choice.  Thanks @dcasati!

**Comment by dcasati** [comment]
I'm on it.

**Comment by dcasati** [comment]
Here's the PR: #131
