### ISSUE TITLE
missing metric (oomKilledContainerCount ) when creating cluster with ARM template

### ISSUE THREAD

**Issue by mracfa** [mspnp/aks-secure-baseline#122]
Hi,
On step 5 (05-aks-cluster) it fails the creation of the cluster if we use the ARM template due to this missing metric: **oomKilledContainerCount**:

```bash
maabre@MAABRE-BOOK2:/mnt/c/Users/maabre/wls_aks/git/aks-secure-baseline$ az deployment group create --resource-group rg-bu0001a0008 --template-file cluster-stamp.json --parameters targetVnetResourceId=$TARGET_
VNET_RESOURCE_ID k8sRbacAadProfileAdminGroupObjectID=$K8S_RBAC_AAD_PROFILE_ADMIN_GROUP_OBJECTID k8sRbacAadProfileTenantId=$K8S_RBAC_AAD_PROFILE_TENANTID appGatewayListenerCertificate=$APP_GATEWAY_LISTENER_CERT
IFICATE aksIngressControllerCertificate=$AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64
Deployment failed. Correlation ID: 009f4644-47b3-4846-a88d-9db844f68583. {
  "Code": "BadRequest",
  "Message": "The following metric name(s) were not found: oomKilledContainerCount. Please note that for custom metrics, the relevant metric namespace must be specified. Activity ID: 93208c19-930f-425a-a71b-e182a78937a9."
}
```

Can you please check?

**Comment by ckittel** [comment]
Interesting.  We hit that with two other ones as well and had to remove them from the deployment.  I wonder if it's regional.  What region were you headed into?  To bypass this, simply remove the `Microsoft.Insights/metricAlerts` resource for that one from `cluster-stamp.json`.  I know alerts are technically `global` for region, but there might be something else going on preventing the deployment.  I bet if you drop this from the template, and after this is deployed, you go into the portal "<cluster>->Insights->Recommended alerts" and find the (now) three that would be sitting at disabled, you could enable them from there.  There seems to be some disconnect between how the portal gets away with creating these vs ARM template.  Let me know what you find, I'd love to get to the bottom of this.

**Comment by ckittel** [comment]
On the region topic, I winder if you'll find you're in a region that is not on the following list?
<https://docs.microsoft.com/azure/azure-monitor/platform/metrics-custom-overview#supported-regions>  -- Interestingly, even `eastus2` had an issue with two of the alerts when I deployed via ARM template -- so not really sure yet what's going on.

**Comment by ckittel** [comment]
We're going to remove the automatic creation of these 12 alerts for now to eliminate any additional friction around them for yourself and others.  I've updated the ARM template to have them in there, but conditionally disabled (always `false`). [PR @ #123]   You can enable all 12 of these via the portal after deployment (in the location I mentioned above).  We're going to track down what it will take to reliability get this in the base template, so we can honor the IaC tenant here end to end.

Thank you!

**Comment by mracfa** [comment]
Hi @ckittel , i just followed the documentation, so i used everything exactly the same. On this case, if i'm not wrong it was eastus2.

**Comment by ckittel** [comment]
Thank you for the info.  The PR for the removal of them has just landed.  I'm tracking the "readding of them" in #117 .  Feel free to follow along in there -- I'm going to close this specific issue, but if you want to keep a conversation going in here, we can.  Thanks again!
