### ISSUE TITLE
Deployment failing with below error.

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#13]
Deployment failed. Correlation ID: b6887f5f-84ef-4374-ac6e-b25a25b57392. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by ferantivero** [comment]
thanks for sharing this @nitinkhandelwal26 could you please what path you have followed to deploy the cluster? have you try to deploy this more than one AKS cluster?

**Comment by nitinkhandelwal26** [comment]
Thanks for your response. We have followed manual using ARM templates, we are now getting an error related to certificates, trying to resolve the same, we have used your scripts only to generate certificates in Linux vm:
crt  location=eastus
Deployment failed. Correlation ID: b0a6fada-0cbc-49e3-9e77-25863e96a73f. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ApplicationGatewayKeyVaultSecretException",
        "message": "Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-zg6gqwsidy4fi'. See details below:",
        "details": [
          {
            "code": "ApplicationGatewaySslCertificateInvalidData",
            "message": "Data or Password for certificate /subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-zg6gqwsidy4fi/sslCertificates/apw-aks-zg6gqwsidy4fi-ssl-certificate is invalid."
          },
          {
            "code": "ApplicationGatewayTrustedRootCertificateInvalidData",
            "message": "Data for certificate /subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-zg6gqwsidy4fi/trustedRootCertificates/root-cert-wildcard-aks-ingress-contoso is invalid."
          }
        ]
      }
    ]
  }
}

**Comment by ferantivero** [comment]
great to hear you guys troubleshooted it @nitinkhandelwal26 please ensure you have got values for the env variables:

1. `APP_GATEWAY_LISTENER_CERTIFICATE`
1. `AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64`

These are set from https://github.com/mspnp/aks-secure-baseline/blob/73ba0003b6d373258a8c319c1abc57b5ec2bed98/02-ca-certificates.md

**Comment by nitinkhandelwal26** [comment]
@ferantivero Thanks for the response, now below error is there :

Deployment failed. Correlation ID: e96f1f76-fd2b-4c51-bc7c-d11b7ea3c520. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}

**Comment by ckittel** [comment]
That's the same error message you posted originally.  Have you validated you have the permissions necessary to perform role assignments and grant other users the same?  This is covered in our [pre-req section, under the first step](https://github.com/mspnp/aks-secure-baseline/blob/main/01-prerequisites.md#steps).

**Comment by nitinkhandelwal26** [comment]
@ckittel I am following exactly what is given in pre-req section, but it's giving same error now, I have already registered in AAD V2 and that service principal attache reference role.
![image](https://user-images.githubusercontent.com/10863548/88068321-ac506a80-cb8d-11ea-8000-e9f91706a686.png)

Now I am allocating Owner role to this and retrying.

**Comment by nitinkhandelwal26** [comment]
my id from where I am deploying this AKS application is having Global admin role and owner access to the subscription.

**Comment by ferantivero** [comment]
thanks for sharing this information @nitinkhandelwal26, 

It seems some `Role Assignments` will need to be re-created. Please let's try to execute the following troubleshooting steps:

1. identify Role Assignments that are failing to be deployed: ` az deployment operation group list -g <resource-group> -n <failed-deployment-name> --query "[?properties.statusMessage.status=='Failed']"`
1. delete the `Role Assignments` that finished with the code `RoleAssignmentUpdateNotPermitted` by using their field `id` (command shared above might help): `az role assignment delete --ids <space-separated-failed-role-assignment-ids>`
1. re-deploy the ARM template

**Comment by nitinkhandelwal26** [comment]
Execution of step 1 gave below error:
az deployment operation group list -g rg-bu0001a0008 -n cluster-stamp --query "[?properties.statusMessage.status=='Failed']"
[
  {
    "id": "/subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-bu0001a0008/providers/Microsoft.Resources/deployments/cluster-stamp/operations/C985C0A5474C9CA6",
    "operationId": "C985C0A5474C9CA6",
    "properties": {
      "duration": "PT4.6434236S",
      "provisioningOperation": "Create",
      "provisioningState": "Failed",
      "request": null,
      "response": null,
      "serviceRequestId": "98d11669-10c6-4f6c-bc4a-0c9ff1e1da4d",
      "statusCode": "Conflict",
      "statusMessage": {
        "error": {
          "code": "ResourceDeploymentFailure",
          "details": [
            {
              "code": "DeploymentFailed",
              "details": [
                {
                  "code": "BadRequest",
                  "message": "{\r\n  \"error\": {\r\n    \"code\": \"RoleAssignmentUpdateNotPermitted\",\r\n    \"message\": \"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"\r\n  }\r\n}"
                }
              ],
              "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details."
            }
          ],
          "message": "The resource operation completed with terminal provisioning state 'Failed'."
        },
        "status": "Failed"
      },
      "targetResource": {
        "id": "/subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-enterprise-networking-spokes/providers/Microsoft.Resources/deployments/EnsureClusterSpHasRbacToVNet",
        "resourceGroup": "rg-enterprise-networking-spokes",
        "resourceName": "EnsureClusterSpHasRbacToVNet",
        "resourceType": "Microsoft.Resources/deployments"
      },
      "timestamp": "2020-07-21T15:18:36.311420+00:00",
      "trackingId": "125e561f-03d6-4ddb-8b8d-8684aeae692c"
    },
    "resourceGroup": "rg-bu0001a0008"
  }
]



On Step 2 in deletion of Role Assignment.
az role assignment delete --ids /subscriptions/c824e797-2017-4901-91d4-5254ae8c1cf8/resourceGroups/rg-enterprise-networking-spokes/providers/Microsoft.Resources/deployments/EnsureClusterSpHasRbacToVNet

Getting below error:

The api-version '2018-09-01-preview' is invalid. The supported versions are '2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.
 

So, need to change API version to 2020-06-01 instead of 2018-09-01-preview mentioned in ARM template. You also change API version in Cluster-Stamp.json.

Will try it tomorrow and keep you updated. Thanks for all your support @ckittel @ferantivero

**Comment by ferantivero** [comment]
@nitinkhandelwal26 to obtain the proper `id` for step 2 that needs to be deleted, please execute the following command:

```bash
az role assignment list --all --query "[?contains(scope,'rg-enterprise-networking-spokes')].id" -o tsv
```

if you get more than one result from above execution, please let's ensure the role assignment you are about to delete correspond to your own deployment instance.

**Comment by nitinkhandelwal26** [comment]
Thanks for your input @ferantivero @ckittel , After adding to owner role in Azure AD group I was able to provision the cluster-stamp.json template but now stuck in Azure policy part in 07-workload-prerequisites.md

Confirm policies are applied to the AKS cluster

kubectl get constrainttemplate

it's giving no resource exists.
then I deployed a complete template and added WAF public IP in /etc/hosts file, still it's not accessible.
Will try again tomorrow, and keep you updated.

**Comment by ckittel** [comment]
`kubectl get constrainttemplate` -- I got that as well, but was able to proceed.  @ferantivero -- can we clarify what the "correct" response should be to that command.  After I got the same message as @nitinkhandelwal26 I just moved on and it all worked in my last dry run yesterday.

**Comment by ferantivero** [comment]
thanks for pointing this out @nitinkhandelwal26 we solved an issue that prevented from getting deployed the Azure Policy for Kubernetes, and also added some details to validate the outcome from `kubectl get constrainttemplate`.

If you are really looking forward to this feature, please consider re-creating the AKS cluster to ensure Azure Policy is properly deployed as well as avoid `RoleAssignmentUpdateNotPermitted`:

1. delete the cluster first
1. delete all the Role Assignments 
1. deploy the `cluster-stamp` again.

Please let us close this issue for now as it seems the original post had been already addressed. But please do not hesitate in re-open this one or create new issues if necessary.
