### ISSUE TITLE
URL based filtering from specific IP address

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#139]
Hello Team,

We have public URL exposed via Application Gateway:
https://www.abc.com/portal - hosting public portal that accept all external traffic.
https://www.abc.com/restapi - hosting public rest API that accept traffic from specific list of public IPs.

Please suggest recommendations whether we can use existing app gateway waf/Traefik ingress controller to achieve this objective or do we have to introduce any other component on this architecture like API management or traffic manager etc..

Request your guidance here..

**Comment by ckittel** [comment]
You can certainly continue to use Azure Application Gateway to handle this.  This baseline simply uses `Basic` routing, but what you're looking for is `PathBasedRouting` based routing. This is a change to the cluster-stamp.json App Gateway configuration.  Check out [the documentation for path-based routing](https://docs.microsoft.com/azure/application-gateway/url-route-overview#pathbasedrouting-rule).

Then, once you have it set up to be path based, then you can use [rewrite rules](https://docs.microsoft.com/azure/application-gateway/rewrite-http-headers-url#server-variables) to reject traffic. This means though that your App Gateway is still being invoked (working) for requests it shouldn't handle.

Traffic Manager wouldn't be any help for you here.  API Management could be used, but I wouldn't recommend it.  It'll add a bunch of costs and complexity.  See if you can solve for your needs within the App Gateway, and if that doesn't work for you, we can talk about how you can add additional components to solve for this.

**Comment by nitinkhandelwal26** [comment]
@ckittel Thank you so much for your guidance..
