### ISSUE TITLE
container security service (Aquasec or Twistlock)

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#140]
Hello Team,

Any plan on implementation of Container security service (Aquasec or Twistlock)?

**Comment by ckittel** [comment]
Services like Aquasec, Twistlock, etc will likely never be part of the baseline version here.  I'm currently working on a "Regulated" environments variant of this baseline in which concerns like this are significantly more common. That said, I'm not sure how easy it's going to be to demonstrate any of these features in a way that doesn't make the deployment/explanation process a burden to work through. Even in there, we might only be able to mention services like that vs giving a implementation.  If you can help us consider an easy way to demonstrate an ISV's solution like this without requiring licensing agreements being held by our learners or without complicating the narrative (we're teaching 201 level content in this baseline), I'm open to suggestions.  It's a very reasonable "next step" on your journey.

**Comment by ckittel** [comment]
Going to close the question for now.  If you do have any suggestions on the best way to teach users about these features, please do let me know.
