### ISSUE TITLE
nodes is forbidden

### ISSUE THREAD

**Issue by rovin-ms** [mspnp/aks-secure-baseline#146]
When attempting to call `kubectl get nodes`, an error is received: 

Error from server (Forbidden): nodes is forbidden: User "xxxxx@microsoft.com" cannot list resource "nodes" in API group "" at the cluster scope

Also, during the AD setup the following command generates this error message:

export AADOBJECTID_USER_CLUSTERADMIN=$(az ad user create --display-name=${AADOBJECTNAME_USER_CLUSTERADMIN} --user-principal-name ${AADOBJECTNAME_USER_CLUSTERADMIN}@${TENANTDOMAIN_K8SRBAC} --force-change-password-next-login --password ChangeMebu0001a0008AdminChangeMe --query objectId -o tsv)
ERROR: Insufficient privileges to complete the operation.

**Comment by shubhammicrosoft1** [comment]
Hi @rovin-ms  

1. First error is because of second error that you have mentioned.
2. Your AD is not configured appropriately with AKS because you don't have sufficient rights to perform write rights over AD 

You can follow below article to make those things work

[https://docs.microsoft.com/en-us/azure/aks/managed-aad](url)

**Comment by ckittel** [comment]
Hey there @rovin-ms -- as @shubhammicrosoft1 mentioned, you'll want to ensure that the user you created, it also assigned to a group that has been granted k8s RBAC permissions to perform that action.  The simplist being a ClusterRoleBinding of ClusterAdmin.  This is the purpose of the group + tenant ID that is passed into the ARM template.  Feel free to reach out to me for any additional troubleshooting necessary (here or on Teams, whatever works for you).

**Comment by rovin-ms** [comment]
Thanks @ckittel and @shubhammicrosoft1. I created my own AD group after I posted here and everything worked. I just thought this should be documented for others that come across this issue when going through the steps. Your work is much appreciated!

**Comment by ckittel** [comment]
Glad it works for you.  If you have any more questions @rovin-ms, don't hesitate to ask. Cheers.
