### ISSUE TITLE
There is no Architecture Diagram or network Diagram available.

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#15]
Hello Team,

Request you to please provide a high level and low-level architecture diagram for this implementation and also better to provide a deciding factor in design decision eg: why application gateway used here, why used Traefik ingress controller is used?

Just a side note: Network topology diagram which is mentioned in the First page is not available. Please check the below URL:
https://camo.githubusercontent.com/611715e81294cd982921606ca9707d1ee65f4584/68747470733a2f2f646f63732e6d6963726f736f66742e636f6d2f617a7572652f6172636869746563747572652f7265666572656e63652d617263686974656374757265732f636f6e7461696e6572732f616b732f7365637572652d626173656c696e652f696d616765732f7365637572652d626173656c696e652d6172636869746563747572652e706e67

Regards

**Comment by ckittel** [comment]
Thank you. The correct link for the diagram is referenced.  Also, make sure you've read the actual reference architecture documentation that goes with this reference implementation.  This implementation is tightly coupled to [the architecture desribed here](https://docs.microsoft.com/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks).

**Comment by nitinkhandelwal26** [comment]
Thank you very much @ckittel . Just some more considerations, can you please answer.
>> Any guidance on how to use a persistent volume claim like Azure Disk for stateful workloads.
>> Any guidance on certificates for WAF in case of multi-workload requirement, like should it be bicycle.contoso.com or should we procure wild card certificate for *.bicycle.contoso.com as well - for the client-facing workload. your response will be highly appreciated as we are designing for big client.

**Comment by nitinkhandelwal26** [comment]
Also Any guidance on AGIC or Traefik ingress controller selection?
