### ISSUE TITLE
Wait for Traefik to be ready

### ISSUE THREAD

**Issue by rovin-ms** [mspnp/aks-secure-baseline#152]
Step 7 from here: https://github.com/rovin-ms/aks-secure-baseline/blob/main/08-secret-managment-and-ingress-controller.md

kubectl wait -n a0008 --for=condition=ready pod  --selector=app.kubernetes.io/name=traefik-ingress-ilb --timeout=90s

produces this error:
error: no matching resources found

**Comment by ckittel** [comment]
@rovin-ms and I proceeded to troubleshoot his issue offline.  I'm going to close this out with no action on this side (feel free to open up again if necessary)
