### ISSUE TITLE
Traefik ingress control pods are not in ready state

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/aks-secure-baseline#156]
Hi Team,
I am facing issue with  traefik ingress controller, pods are not in ready state. Azure internal load balancer got provisioned.
please find the attached screenshots for reference.

![image](https://user-images.githubusercontent.com/57993345/107541050-bc44a000-6bec-11eb-882d-c07907165130.png)
![image](https://user-images.githubusercontent.com/57993345/107541087-c797cb80-6bec-11eb-8080-968cff31f4c0.png)
![image](https://user-images.githubusercontent.com/57993345/107541134-d1213380-6bec-11eb-9621-9499a3e36f82.png)
![image](https://user-images.githubusercontent.com/57993345/107541184-df6f4f80-6bec-11eb-9232-646819484273.png)
![image](https://user-images.githubusercontent.com/57993345/107541257-f150f280-6bec-11eb-8634-f121cf7fde4e.png)
![image](https://user-images.githubusercontent.com/57993345/107541303-ff9f0e80-6bec-11eb-8556-e359d3c1030d.png)

could you please help us to fix this issue.

**Comment by rambabu0063** [comment]
Hi Team,

issue has been resolved.

thank you

**Comment by ferantivero** [comment]
thanks for confirming @rambabu0063, please let's go ahead and close this issue.
