### ISSUE TITLE
clarification on regional hub vnet

### ISSUE THREAD

**Issue by Mahesh-MSFT** [mspnp/aks-secure-baseline#164]
in the guidance on [Deploy the Hub-Spoke Network Topology](https://github.com/mspnp/aks-secure-baseline/blob/main/04-networking.md), a hub vnet is deployed using template `networking/hub-default.json`. this vnet is peered with aks spoke vnet. 

then another "regional" vnet hub is created using `networking/hub-regionA.json` template. 

guidance on [AKS baseline Network Topology](https://github.com/mspnp/aks-secure-baseline/blob/main/networking/topology.md) doesn't mention anything about "regional" vnet hub. the [network topology diagram](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#network-topology) doesn't depict this "regional" hub vnet as well.

guidance on [Deploy the Hub-Spoke Network Topology](https://github.com/mspnp/aks-secure-baseline/blob/main/04-networking.md) talks about following points.

1. ...the hub can no longer run off of the generic hub template...
2. ...to forever represent this specific hub and the features this specific hub needs...
3. ...to support its spokes' requirements...

i am looking for following information.

1. why does hub can no longer in generic template?
2. what *specific* features does "regional" hub needs?
3. what *specific* spoke requirement does "regional" hub supports?
3. why do we need 2 hub vnets?

thanks

**Comment by ckittel** [comment]
Going to close the question for now, if you wish to continue the conversation please don't hesitate to do so; here or in a new issue.  Thanks.
