### ISSUE TITLE
[Azure Advisor Recommendation]  Vulnerabilities in Azure Container Registry images (memcached)

### ISSUE THREAD

**Issue by v-fearam** [mspnp/aks-secure-baseline#168]
memcached, used by flux on flux.yaml
![image](https://user-images.githubusercontent.com/62260324/109537483-afa1c200-7a9d-11eb-8d0a-4f9428531d17.png)
The current version used is 1.5.20, and the latest 1.6.9.
I don't know if the new image solved that issue and if it is compatible the current flux version. 
However, we need to investigate and try to solve the security issue.

**Comment by ckittel** [comment]
This will go away with #144.

If that work gets delayed, we can try to test upgrading that sidecar image to see how well it works with our usage of flux v1

**Comment by ckittel** [comment]
Going to close this issue with the progress planned around #144 in the next sprint.
