### ISSUE TITLE
cluster-stamp - ResourceNotFound error

### ISSUE THREAD

**Issue by learnercrypto** [mspnp/aks-secure-baseline#193]
Hey Folks, I don't know if I am doing something wrong or cluster-stamp couldn't rum AKS deployment and exit with the below message:
Deployment failed. Correlation ID: f3913046-d719-463e-b373-d20fb2fe940a. {
"code": "ResourceNotFound",
"message": "The Resource 'Microsoft.ContainerService/managedClusters/aks-tgp5w6mq6ev7q' under resource group 'rg-bu0001a0008' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix Activity ID: e18f611e-ec48-426e-850c-dc7385b1e3d6."
}
I assumed the problem is because of limits in Compute-VM for Total Regional vCPUs, It is fixed but yet there is no progress. Could you please advise the way forward?

**Comment by ckittel** [comment]
Check out the `Deployment` in the azure portal, see if there were any other resources that had errors deployment.  It's possible that the cluster failed to deploy, so something that depended on it failed to deploy.  I can't provide any specific help here, but if you can take a look at the deployments on the AKS resource group, you should be able to get some more details.  Let us know what you find.

**Comment by learnercrypto** [comment]
Hello again,
I learned that inside cluster-stamp.json template address the resource group named 'bu0001a0008-00' but in 05-aks-cluster.md in step 1, it makes another name by az group create --name rg-bu0001a0008 --location eastus2
So I changed the name and it works after 10-15v min again stopped here:
Deployment failed. Correlation ID: 5251ec58-2171-4c1a-aae1-e8bf3239dfe3. {
  "code": "ResourceNotFound",
  "message": "The Resource 'Microsoft.ContainerService/managedClusters/aks-ab3ovorw742dk' under resource group 'bu0001a0008-00' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix Activity ID: 494f6be6-9191-4d07-ad4d-6dac3d55c14a."
}

Perhaps someone should control this JSON for consistency of resource group name, I don't know, but please let me know if you have some idea.

**Comment by ckittel** [comment]
I'm sorry you are running into this. Can you help point out where `bu0001a0008-00` is being referenced as a resource group name? I must be missing it.

A search that might help: https://github.com/mspnp/aks-secure-baseline/search?q=bu0001a0008-00&type=

**Comment by learnercrypto** [comment]
Frankly, I am a newbie and I don't know if my understanding is accurate but in my deployment experience in few cases like application gateway or cluster, variables like nodeResourceGroupName or clusterName are taking the value that is not necessarily equal to dependsOn conditions. Perhaps this is the reason that with resource group named rg-bu0001a0008 cluster-stamp.json halted quickly but when I change the resource group to bu0001a0008-00 it worked more and then it halted on the application gateway dependsOn condition. perhaps bu0001a0008 or rg-bu0001a0008 or bu0001a0008-00 are confusing (at least for me) and also, I am not sure if we make all resources in a name that we check their availability with dependsON. Sorry for the general address and not provide a code-line-specific explanation, I am trying to understand the scripts and I am not capable to find the exact line that has an issue right now.

**Comment by ckittel** [comment]
Yeah, I can't seem to find it either, which is why I was hoping you'd have more details. We run through this deployment frequently (at least weekly) and haven't run into this situation. Any further details would be of great assistance.

`dependsOn` only is allowed to reference items created in the same deployment, and it does it's own validation to ensure those resources exist before deploying the dependant resource.

**Comment by ckittel** [comment]
I'm going to go ahead and close the issue.  However, if there is more that we can help you with, please feel free to re-open, don't treat this as the end of the conversation if you still believe we made a mistake in our instructions here or could make things clearer.  Cheers!
