### ISSUE TITLE
Certificate password error

### ISSUE THREAD

**Issue by mzrzz3** [mspnp/aks-secure-baseline#198]
What is the expected value for the password when generating the appgw.pfx? The instructions in section 02-ca-certificates.md has the following command: Note that the actual password is not specified.

` openssl pkcs12 -export -out appgw.pfx -in appgw.crt -inkey appgw.key -passout pass:`

During deployment in section 05-aks-cluster.md, the cluster deployment fails with the following error:

`az deployment group create -g rg-bu0001a0008 -f cluster-stamp.json -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} clusterAdminAadGroupObjectIADMIN} k8sControlPlaneAuthorizationTenantId=${TENANTID_K8SRBAC} appGatewayListenerCertificate=${APP_GATEWAY_LISTENER_CERTIFICATE} aksIngressControllerCertificate=${AKS_INGRESS_CONTROLLER_CERTIFICATE_
Deployment failed. Correlation ID: df73c089-c448-4220-8220-e9554490d164. {
  "status": "Failed",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "ApplicationGatewayKeyVaultSecretException",
        "message": "Problem occured while accessing and validating KeyVault Secrets associated with Application Gateway '/subscriptions/943f5205-0d30-49cd-8267-11bb82be4ba0/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-27knvurjjdwtq'. See details below:",
        "details": [
          {
            "code": "ApplicationGatewaySslCertificatePasswordIncorrect",
            "message": "Password specified for certificate /subscriptions/943f5205-0d30-49cd-8267-11bb82be4ba0/resourceGroups/rg-bu0001a0008/providers/Microsoft.Network/applicationGateways/apw-aks-27knvurjjdwtq/sslCertificates/apw-aks-27knvurjjdwtq-ssl-certificate is incorrect."
          }
        ]
      }
    ]
  }
}`

I have tried to deploy the reference architecture a couple of times but this issue is a blocker for me.

Any assistance much appreciated.

Thanks!

**Comment by ckittel** [comment]
Sorry you are experiencing this. No password is provided on that self-signed cert for this walkthrough, since the self-signed cert is just for demo purposes so you don't need to actually procure a cert to get though this content :)

Not sure what password is being talked about in your error message.  Did you provide one?  If not, we have not set up the deployment to support a password here, and if not, odd, as we've not experienced this before.  Can you tell us more about what's in that certificate key vault record?  If you pull that value out of key vault directly, it is a valid cert?

@ferantivero -- do you have any thoughts on this error?  With all the deployments that have been done on this content day after day, no one has run into this before -- do you have any idea on why AppGW would throw this error by chance?

**Comment by ferantivero** [comment]
yeah, we hadn't faced this in the past and yes, no pass should be passed. The error is pretty clear though.

@mzrzz3 could you please confirm you haven't attempt to enter a pass while generating the cert?

**Comment by mzrzz3** [comment]
I can confirm that I am not providing a password when the pfx is created. I also did a test to manually import the pfx into Windows certificate manager without a password. This worked OK without an error. If I do provide a password, certificate manager will not import the certificate. I think that shows that the certificate is OK.

I am wondering if there is something on the App Gateway side that is expecting a password on the to be required? 

I will redeploy later this morning and provide an update.

Any additional feedback welcome.

Thanks.

**Comment by ckittel** [comment]
@mzrzz3 eager to see if you find out more. Maybe something changed on AAG in the last day or two. We had an end-to-end deployment of this solution eariler this week.  I don't think anyone will be deploying it today, internally here, but we will be next week.  Let us know what you find out.  Looks like this error can come up in other odd situations as well, for example here is a place where an unsupported encryption algo was used: MicrosoftDocs/azure-docs#54393  -- so maybe something else is going on, mascarading itself as a "password" issue?

**Comment by mzrzz3** [comment]
A couple of things I notice.

1) Two certificates are deployed into key vault in the secrets store and NOT in the key vault certificates store.
2) I tried using the Azure Portal to fix the http-listener in app gateway to give it the certificate. However, no certificate of course is found in the key vault (see point 1) and when uploading the .pfx, I am required to provide a password.

<img width="483" alt="certs-as-secrets" src="https://user-images.githubusercontent.com/7062176/117501405-9e64ae00-af43-11eb-80a6-5ac410c24984.png">
<img width="341" alt="cert-not-in-vault" src="https://user-images.githubusercontent.com/7062176/117501406-9e64ae00-af43-11eb-847e-9abee45e8612.png">
<img width="317" alt="cert-needs-password" src="https://user-images.githubusercontent.com/7062176/117501407-9e64ae00-af43-11eb-99bd-743909799b07.png">

Thoughts?

**Comment by ckittel** [comment]
@mzrzz3 are you running on Mac by chance?  We are potentially tracking another macos user running into a somewhat situation.

**Comment by mzrzz3** [comment]
@ckittel Windows 10 but using WSL (Ubuntu 20.04.2 LTS) because of all the bash scripts.

**Comment by ckittel** [comment]
We haven't had any other reports of this.  Were you able to resolve the issue?  We cannot replicate on our side.  One additional thought is to make sure you're using bash (vs something like zsh -- we've had subtle syntax issues in the past based on the interpreter used.

I'm going to go ahead and close the issue, but you're welcome to reopen if you want to continue the conversation.

**Comment by mzrzz3** [comment]
@ckittel we ended up taking the concepts from the reference architecture and building out an implementation using Terraform. It would have been useful to see it working end-to-end but we got the information/recommendations we needed anyway. Thanks for following up.

**Comment by ckittel** [comment]
Perfect, that's one of the main reasons this reference implementation is here -- simply as a reference. :)  Glad to hear you were able to move forward.
