### ISSUE TITLE
Guidance on persistent volume uses

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#210]
Hello Team,

Is any implementation around PV is in your backlog. I understand in current implementation workload is stateless but any plan around showcase references implementation on Persistent Volume in your product backlog?

Regards,

**Comment by ckittel** [comment]
We'd love to tell a stateful story at some point, but it is currently not officially on on backlog. 

cc: @JasRobe for a customer signal.

**Comment by ckittel** [comment]
Going to close this issue as I think @JasRobe from our strategy team has captured this now.  We know telling a "stateful story" was hopefully going to be our next piece of content, but not currently sure of the timeline on that.
