### ISSUE TITLE
Deployment to spoke RG is failing with a Bad Request error when creating peering with hub vnet

### ISSUE THREAD

**Issue by rajnemani** [mspnp/aks-secure-baseline#216]
Deployment to spoke RG is failing with a Bad Request error when creating peering with hub Vnet. Appreciate any ideas on what could be going wrong

**Comment by ckittel** [comment]
Do you have any more details to share?  I'm afraid based on this limited information, I cannot guess what might be the problem.

**Comment by rajnemani** [comment]
Sorry for the late reply.  I should have checked here earlier. I will try to get the error stack and get back to you.  Thank you for following up.

**Comment by tasb** [comment]
Hi, I'm getting the same error too:

{"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD HTML 4.01//EN\\\"\\\"http://www.w3.org/TR/html4/strict.dtd\\\">\\r\\n<HTML><HEAD><TITLE>Bad Request</TITLE>\\r\\n<META HTTP-EQUIV=\\\"Content-Type\\\" Content=\\\"text/html; charset=us-ascii\\\"></HEAD>\\r\\n<BODY><h2>Bad Request - Invalid URL</h2>\\r\\n<hr><p>HTTP Error 400. The request URL is invalid.</p>\\r\\n</BODY></HTML>\\r\\n\"\r\n  }\r\n}"}]}}

**Comment by ckittel** [comment]
@tasb at the same spot as the OP?

**Comment by tasb** [comment]
I get this error deploying spoke networking. 
I've checked and all the resources are created unless VNET peering

**Comment by ckittel** [comment]
What resource is surfacing this error? You can view the deployment by looking at the spokes resource group and clicking "Deployments" - there you'll be able to see the resource that is failing and can dig in for more details. Anything you can share will be helpful.

**Comment by ckittel** [comment]
I'm going to go ahead and close the issue with no response.  But please, don't take that to mean we won't continue to help. If you wish to reengage, just please open the issue back up.  Cheers.
