### ISSUE TITLE
More Info on Dev/Test Config

### ISSUE THREAD

**Issue by thepaulmacca** [mspnp/aks-secure-baseline#227]
Whilst this is a great starting point for people new to AKS, what I feel would really make this complete is how to configure a cluster for Dev/Test as well

It's all well and good spinning up a Prod cluster, but the Dev/Test side of this also needs to be accounted for in my opinion, and I imagine most would have a separate cluster for that with cheaper SKUs and fewer nodes etc

Will this information be added in future?

**Comment by thepaulmacca** [comment]
Appreciate the reply. I think this would be the next type of question people will be asking, so would be good to see this information somewhere soon. I'm sure others would agree

**Comment by ckittel** [comment]
Going to ping two folks to capture this customer request signal: @georgewallace & @JasRobe

**Comment by ckittel** [comment]
@georgewallace, @jamcneil, and @JasRobe -- has this been captured as a content request signal for C&L? If so, let me know so that I can close the issue.

**Comment by ckittel** [comment]
Confirmed that this has been captured in our internal backlog by @JasRobe. This wouldn't be the repo that holds that guidance, and there isn't a repo right now that exists that would. So for now I'll be closing the issue. Thanks @thepaulmacca for the signal on this.
