### ISSUE TITLE
Key vault with RBAC instead of access policies

### ISSUE THREAD

**Issue by stephaneey** [mspnp/aks-secure-baseline#232]
Hi,

Wouldn't it be better to switch to key vault RBAC instead of vault access policies? In the template, you currently create vault policies for the user-assigned identities, where it'd be better to leverage RBAC instead, in order to keep a single pane of glasses to manage authorizations.

Thanks

**Comment by ckittel** [comment]
Indeed @stephaneey, Azure RBAC would have also been a valid solution, and I think it's time we make the migration.  I'll add this to our backlog, and will keep this issue open until we get time to address it.

**Comment by ckittel** [comment]
@stephaneey -- the reference implementation was updated now to use Azure RBAC instead of access policies.  That opened a bit of a can of worms :) but I'm glad it was done.  Thanks for the nudge!

**Comment by stephaneey** [comment]
Well done

**Comment by DreamRivulet** [comment]
It seems that appgw with managed identity  can't work with Key Vault RBAC.

**Comment by ckittel** [comment]
> It seems that appgw with managed identity  can't work with Key Vault RBAC.

Can you add some more context about your experience?
