### ISSUE TITLE
Hub and spoke diagram needs correction

### ISSUE THREAD

**Issue by abymsft** [mspnp/aks-secure-baseline#233]
The hub should be taking the traffic from the internet (Azure Firewall **inbound**) and not the spoke. Please check the attached image. I couldn't find the visio/ppt to edit the diagram. Would have raised a PR.

![image](https://user-images.githubusercontent.com/50873759/133989829-47b1fdd5-9781-43c6-955d-1316abf13cca.png)

**Comment by ckittel** [comment]
The network topology in this reference implementation does not use Azure Firewall as part of the ingress flow of traffic.  Public internet for workload traffic enters App Gateway (which could live in the hub if desired).  Firewall is for egress traffic (that is, traffic originating in the cluster.)

Azure Firewall and Application Gateway can live in one of three topologies.

Azure Firewall -> Application Gateway -> Compute  && Compute -> Azure Firewall
Application Gateway -> Azure Firewall -> Compute && Compute -> Azure Firewall
Application Gateway -> Compute && Compute -> Azure Firewall.

The third is the topology used in this reference implementation.  Check out [this article on the pros and cons and considerations of all three topologies](https://docs.microsoft.com/azure/architecture/example-scenario/gateway/firewall-application-gateway).

All of them are valid use cases.  But the diagram does show what's happening in THIS reference implementation.

**Comment by abymsft** [comment]
Thanks for the clarification @ckittel
