### ISSUE TITLE
Unable to use NFS shares with Azure File CSI driver on 1.21.x

### ISSUE THREAD

**Issue by ccyflai** [mspnp/aks-secure-baseline#249]
A fresh build 1.21.x cannot use NFS share with Azure File CSI driver.  It seems to be permission problem.  The agentpool managed identity (Object ID 09827827-a1a4-45a6-bdf9-12117d3b85b1) cannot read cluster node subnet.

  Warning  ProvisioningFailed    28m (x14 over 52m)    file.csi.azure.com_aks-npsystem-41147333-vmss000002_f3b397f6-b448-41e6-935a-c3a58b98cab4  failed to provision volume with StorageClass "azurefile-csi-nfs": rpc error: code = Internal desc = update service endpoints failed with error: failed to get the subnet snet-clusternodes under vnet vnet-spoke-BU0001A0008-00: &{false 403 0001-01-01 00:00:00 +0000 UTC {"error":{"code":"AuthorizationFailed","message":"The client '09827827-a1a4-45a6-bdf9-12117d3b85b1' with object id '09827827-a1a4-45a6-bdf9-12117d3b85b1' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/8fec5943-6772-4aa8-a1aa-59ef7483fd2b/resourceGroups/rg-aks-eas-st-spoke-01/providers/Microsoft.Network/virtualNetworks/vnet-spoke-BU0001A0008-00/subnets/snet-clusternodes' or the scope is invalid. If access was recently granted, please refresh your credentials."}}}

**Comment by ckittel** [comment]
Hey there @ccyflai, thanks for engaging.  Sorry you ran into this. We have not specifically tested this deployment with anything outside of what is deployed in the reference.  That said, your error is vey interesting and I'd like to learn a bit more.

The error:

> The client '09827827-a1a4-45a6-bdf9-12117d3b85b1' with object id '09827827-a1a4-45a6-bdf9-12117d3b85b1' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/subnets/read' over scope '/subscriptions/8fec5943-6772-4aa8-a1aa-59ef7483fd2b/resourceGroups/rg-aks-eas-st-spoke-01/providers/Microsoft.Network/virtualNetworks/vnet-spoke-BU0001A0008-00/subnets/snet-clusternodes'

seems to indicate that the Azure AD identity `09827827-a1a4-[redacted]` doesn't have enough permissions over your spoke's subnet that contains the cluster nodes `/subscriptions/[redacted]/resourceGroups/rg-aks-eas-st-spoke-01/providers/Microsoft.Network/virtualNetworks/vnet-spoke-BU0001A0008-00/subnets/snet-clusternodes`

Can you let us know what identity that is?  Likely a managed identity, but not sure which is trying to be used.  But if you look at that subnet, you'll see other role assignments made.  Check to see if this identity has those permissions (and it may require more permissions than just the first error mentioned here)

**Comment by ccyflai** [comment]
Tried again using built-in AzureFile CSI storage class, it still have problem.

$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/pvc-azurefile-csi.yaml
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/deploy/example/nginx-pod-azurefile.yaml

![image](https://user-images.githubusercontent.com/1573177/139794332-9ccdadbd-f783-4064-a319-6925935a9b9e.png)

Seemingly, the node pool host was blocked to access the storage account.  After I added the Microsoft.Storage service endpoint in snet-clusternodes, it is able to mount the storage.

**Comment by ckittel** [comment]
Yes, no additional service endpoints or anything are added to the nodes subnet as none are required for this implementation.  You generally wouldn't pre-emptively add security openings to a subnet, unless you knew that was going to be used (which isn't implied in this deployment).  So following the requirements of AzureFile CSI would be required in this, and any other deployment.

If you can get me the identity information that I requested above, that would be interesting to capture as part of this learning.
