### ISSUE TITLE
Github Actions flow has different deployment name

### ISSUE THREAD

**Issue by balteravishay** [mspnp/aks-secure-baseline#26]
When deploying the cluster using Github actions flow (05 - aks cluster, option 3) the deployment name is cluster-stamp-cd and not cluster-stamp.

This causes one of the following steps to break:

07. Obtain the Azure Key Vault details and give the current user permissions to import certificates.
KEYVAULT_NAME=$(az deployment group show --resource-group rg-bu0001a0008 -n cluster-stamp --query properties.outputs.keyVaultName.value -o tsv)

Either the deployment name should be changed in GH Action flow, or the doc need to note this.

**Comment by ferantivero** [comment]
thanks for sharing this @balteravishay, and really nice to see you have followed the GitHub actions path to get your AKS cluster deployed 😸 

PRs are more than welcome in all our repos, so we'd love to receive one from you changing the deploy name from `cluster-stamp-cd` to `cluster-stamp` in the GitHub workflow.

**Comment by ckittel** [comment]
Closing issue.  Thanks for your contribution @balteravishay
