### ISSUE TITLE
Can we use Let's encrypt certificate for standard certificate in production deployment

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#28]
Hi team,

Can we use Let's Encrypt certificate for the standard certificate in production deployment for the ingress controller? or do we need to acquire from a paid CA provider?

For the Azure Application Gateway WAF EV certificate, we will use paid CA certificate providers like entrust.
Q: What is the design consideration for taking an EV certificate here?

Regards,

**Comment by ferantivero** [comment]
@nitinkhandelwal26, Let's Encrypt is a Certificate Authority, so you might want to evaluate to use them based on your requirements. 

Regarding Extended Validation certs, organizations will be subject of more rigorous process conducted by group of selected CA(s), and as a consequence will be vetted or not. This results in more confidence when users see them. By the way, they're displayed differently in the web browsers.

We are closing this issues for now.
