### ISSUE TITLE
Q: why we require WAF when we have Azure Firewall in hub vnet

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#50]
Hello Team, 

Can you please clarify in this implementation

Why you have used Azure Application Gateway WebApplication Firewall when we have Azure Firewall available in hub vnet,
Cannot we route all incoming traffic to Traefik ingress from Azure firewall using UDR in the Route table?

Request you to please explain What is core logic behind that.

Regards,

**Comment by nitinkhandelwal26** [comment]
TLS is not available in Azure Firewall.
https://social.msdn.microsoft.com/Forums/en-US/f0b302b0-8d11-46ff-9045-b8e01e86920b/azure-firewall-support-for-tls?forum=WAVirtualMachinesforWindows
Is this the reason for the same?

**Comment by ckittel** [comment]
Thanks for the question @nitinkhandelwal26.  Azure Firewall is primarily used as an enterprise **egress** control point.  While you can ingress and egress through it, that isn't the desired outcome here.  We want **HTTP traffic** to _ingress and egress through a WAF_, and we want **cluster-originated traffic** to have _a control/choke point (egress) in Azure Firewall_.  This protects you from unwanted traffic escaping your cluster (think exfiltration or command and control traffic).

Azure Firewall doesn't do deep packet inspection ([ModSec Core Rule](https://coreruleset.org/) Evaluation) for HTTP traffic, that's Azure Application Gateway's primary role.  It can also [support custom rules](https://docs.microsoft.com/azure/web-application-firewall/ag/custom-waf-rules-overview), beyond just ModSec rules -- such as IP- and Geo-based filtering.  Azure Application Gateway also has advanced routing features and route manipulation.  It can also support custom rules beyond  It's perfectly suited to handle web traffic - in and out.

You can technically combine the two (daisy chain), at the cost of performance and complexity in your architecture - for most customers, putting a firewall on HTTP ingress isn't the desired behavior, putting a WAF (w/ firewall-like rules) is.

This topic is covered on our [reference architecture document](https://docs.microsoft.com/azure/architecture/reference-architectures/containers/aks/secure-baseline-aks#secure-the-network-flow).

**Comment by nitinkhandelwal26** [comment]
Thank you for explaining this @ckittel.
