### ISSUE TITLE
Do we require  cert-manager with Traefik for LetsEncrypt certificates?

### ISSUE THREAD

**Issue by nitinkhandelwal26** [mspnp/aks-secure-baseline#59]
Hello Team,

Since Traefik ingress used here out of the box provides HTTPS to microservices by leveraging Let's Encrypt (wildcard certificates support).
Do we also require Cert-manager installed with Traefik ingress just like we do in NGINX?

**Comment by ferantivero** [comment]
thanks for this question @nithandelwal26 if you choose the path that integrates Traefik with an ACME provider such us Let's Encrypt, it might be still a good idea to have a platform-managed secret store in place. The reason for this is that in case Let's Encrypt were not reachable the ingress controller could be still operative having this as fallback system to provide backup certificates.

But for the happy path, Traefik could be configured to talk directly to your ACME provider.

**Comment by nitinkhandelwal26** [comment]
Thank you @ferantivero for your response.
Here I got little confused about platform managed secret store, are we talking about azure key vault here as a fall back option or Cert-manager?

**Comment by ferantivero** [comment]
yes @nitinkhandelwal26 I was suggesting you to consider to have your main ACME provider in place + a fallback system that could be platform managed secret storage that provides with back certs, and yes Azure KeyVault might work perfectly in this case. 

Regarding using cert-manager or not with Traefik, I'm seeing from [Use a custom traefik ingress and configure HTTPS](https://docs.microsoft.com/en-us/azure/dev-spaces/how-to/ingress-https-traefik#configure-the-traefik-ingress-controller-to-use-https) it is something being used, and please let me also link you to some mentioning around this from [the Traefik's official docs - ](https://docs.traefik.io/providers/kubernetes-ingress/#letsencrypt-support-with-the-ingress-provider)

**Comment by nitinkhandelwal26** [comment]
Thanks @ferantivero for your reply.
