### ISSUE TITLE
base64 -w is not available on macOS

### ISSUE THREAD

**Issue by neilpeterson** [mspnp/aks-secure-baseline#62]
This doc includes instructions for base64 encoding certificates using `bas64 -w`. The `-w` option is not available on macOS and would rather be `-b 0` which is also the command default so can be omitted.

https://github.com/mspnp/aks-secure-baseline/blob/main/02-ca-certificates.md

![image](https://user-images.githubusercontent.com/7844635/91665167-87aeb300-eaa8-11ea-9d9f-dc7fcfaf5141.png)

**Comment by ckittel** [comment]
Thanks Neil.  I don't have a mac to test on.  If there is a good way that works across all OSes to perform the same thing, could you open a PR for that solution?  Or maybe this needs to be handled in written words?
