### ISSUE TITLE
overlapping service ip range

### ISSUE THREAD

**Issue by jrudley** [mspnp/aks-secure-baseline#93]
In your spoke json, it is hard coded for the service cidr range. It seems like a grey area if this ip space can be reused across different clusters? Overlap with other vnets with which the cluster virtual network peers. If spoke A peers with Spoke B, would that be considered overlapping if set on 2 clusters?
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni

```
Kubernetes service address range: This is the set of virtual IPs that Kubernetes assigns to internal services in your cluster. You can use any private address range that satisfies the following requirements:

Must not be within the virtual network IP address range of your cluster
Must not overlap with any other virtual networks with which the cluster virtual network peers
Must not overlap with any on-premises IPs
Must not be within the ranges 169.254.0.0/16, 172.30.0.0/16, 172.31.0.0/16, or 192.0.2.0/24
Although it's technically possible to specify a service address range within the same virtual network as your cluster, doing so is not recommended. Unpredictable behavior can result if overlapping IP ranges are used. For more information, see the FAQ section of this article. For more information on Kubernetes services, see Services in the Kubernetes documentation.
```

**Comment by ckittel** [comment]
Hey there James.

Are you specifically talking about the choice that this (factitious) network team decided to grant this application team's spoke the range of `10.240.0.0/16` (with the three subnets within that space)?  If this spoke was to ever peer with another spoke (read: if this vnet were to ever peer with another vnet), you wouldn't be able to use the same address space.  Spokes IP address spaces are typically planned and cataloged to ensure no overlap in organizations.  I'm pretty sure that's NOT your question, but wanted to cover it.

The kubernetes service address range, also should NOT overlap with the ACTUAL IP address range of any peered spokes.  So for example we use `172.16.0.0/16` for that range.  "Spoke B"'s address space in your example above should not be within that range -- this could lead to routing confusion when going from the cluster in "Spoke A" to any of those IP addresses.  However, a cluster in "Spoke B" could use the same `172.16.0.0/16` range -- there is no expectation that a cluster in spoke A will directly resolve a virtual ip in the cluster in spoke B.

**Comment by jrudley** [comment]
Thanks, it was the service address range in question. Thanks again for the
reply.
