### ISSUE TITLE
Alert is not generating on P1 after PODFAILED 

### ISSUE THREAD

**Issue by rambabu0063** [mspnp/aks-secure-baseline#96]
Hello Team,
we have configured the Alert rule using your code Podfailephase Alert via ARM template cluster stamp.json  after that we have configured the Alert with email configuration then we forcefully failed one pod  for testing purpose but we are not getting Alert email or any alert notification in portal  from podfailedphase alert rule.

<img width="449" alt="podfailedphase-1" src="https://user-images.githubusercontent.com/57993345/96990181-674d2300-1544-11eb-97f7-9e5b7e107be8.PNG">
<img width="366" alt="podfailedphase-2" src="https://user-images.githubusercontent.com/57993345/96990191-69af7d00-1544-11eb-82ac-b65f7c36a657.PNG">
<img width="382" alt="podfailedphase-3" src="https://user-images.githubusercontent.com/57993345/96990194-6b794080-1544-11eb-8e44-c56a3add7e4d.PNG">

could you please help us to figure it out the missing steps.

**Comment by ckittel** [comment]
@v-fearam -- I think you might be the best person to answer this one. I haven't looked at the alert configuration close enough here to quickly answer.  Anything you might be able to spot from @rambabu0063's question that you can help with?

**Comment by ckittel** [comment]
In the mean time, @rambabu0063 what happens when you execute the query itself?  Any results?  Does anything "look wrong" in the query (e.g. like `clusterName` not getting setting properly, or a parse error of some kind)

This is the query as defined in the ARM template looks something like the following as defined on the docs @ https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-log-alerts

```kusto
let endDateTime = now();
let startDateTime = ago(1h);
let trendBinSize = 1m;
let clusterName = '<your-cluster-name>';
KubePodInventory
    | where TimeGenerated < endDateTime
    | where TimeGenerated >= startDateTime
    | where ClusterName == clusterName
    | distinct ClusterName, TimeGenerated
    | summarize ClusterSnapshotCount = count() by bin(TimeGenerated, trendBinSize), ClusterName
    | join hint.strategy=broadcast (
        KubePodInventory
        | where TimeGenerated < endDateTime
        | where TimeGenerated >= startDateTime
        | distinct ClusterName, Computer, PodUid, TimeGenerated, PodStatus
        | summarize TotalCount = count(),
                    PendingCount = sumif(1, PodStatus =~ 'Pending'),
                    RunningCount = sumif(1, PodStatus =~ 'Running'),
                    SucceededCount = sumif(1, PodStatus =~ 'Succeeded'),
                    FailedCount = sumif(1, PodStatus =~ 'Failed')
                 by ClusterName, bin(TimeGenerated, trendBinSize)
    ) on ClusterName, TimeGenerated
    | extend UnknownCount = TotalCount - PendingCount - RunningCount - SucceededCount - FailedCount
    | project TimeGenerated,
              TotalCount = todouble(TotalCount) / ClusterSnapshotCount,
              PendingCount = todouble(PendingCount) / ClusterSnapshotCount,
              RunningCount = todouble(RunningCount) / ClusterSnapshotCount,
              SucceededCount = todouble(SucceededCount) / ClusterSnapshotCount,
              FailedCount = todouble(FailedCount) / ClusterSnapshotCount,
              UnknownCount = todouble(UnknownCount) / ClusterSnapshotCount
| summarize AggregatedValue = avg(PendingCount) by bin(TimeGenerated, trendBinSize)
```

**Comment by rambabu0063** [comment]
Thank you @ckittel 
will execute the query and share the result.
could you please validate the pod status. 
<img width="603" alt="pod-status" src="https://user-images.githubusercontent.com/57993345/97023934-cd04d380-1573-11eb-93b7-2d7d34ae70f1.PNG">

**Comment by rambabu0063** [comment]
Hi @ckittel 
I have executed the query but did not get any exact log description.


<img width="449" alt="query-result" src="https://user-images.githubusercontent.com/57993345/97025861-400f4980-1576-11eb-9ee6-fc758a3dba5b.PNG">

**Comment by ckittel** [comment]
That's a count per minute of whatever is in your last line of the query. The one I copied above was "pending count". What's yours? Also what is the threshold you have set? Does "2 a minute" cross that threshold?

**Comment by rambabu0063** [comment]
I have used same code as given in  your ARM template 
<img width="950" alt="query" src="https://user-images.githubusercontent.com/57993345/97031485-00e4f680-157e-11eb-84b0-ce9803982f59.PNG">

**Comment by ckittel** [comment]
FailedCount, that's good. The threshold might need to be tweaked for your two failures every minute to be picked up. What we included was a sample for you to tweak based on your needs. Try adjusting the threshold to fit/tune to your test conditions.

**Comment by ckittel** [comment]
@rambabu0063 how's is going?

**Comment by ckittel** [comment]
Been about a week.  Going to close this one.  Feel free to reopen if the above guidance didn't help you solve your question.
